Update goldens for parse tests.

diff --git a/etest_test/parsers_test/bash_test_fixtures/correct_spurious_quote_token.yaml b/etest_test/parsers_test/bash_test_fixtures/correct_spurious_quote_token.yaml
--- a/etest_test/parsers_test/bash_test_fixtures/correct_spurious_quote_token.yaml
+++ b/etest_test/parsers_test/bash_test_fixtures/correct_spurious_quote_token.yaml
@@ -1,53 +1,53 @@
 text: |
-        src_configure() {
-        # Bigloo doesn't use autoconf and consequently a lot of options used by econf give errors
-        # Manuel Serrano says: "Please, dont talk to me about autoconf. I simply dont want to hear about it..."
-        ./configure \
-                $(use java && echo "--jvm=yes --java=$(java-config --java) --javac=$(java-config --javac)") \
-                --prefix=/usr \
-                --mandir=/usr/share/man \
-                --infodir=/usr/share/info \
-                --libdir=/usr/$(get_libdir) \
-                --docdir=/usr/share/doc/${PF} \
-                --benchmark=yes \
-                --sharedbde=no \
-                --sharedcompiler=no \
-                --coflags="" || die "configure failed"
-                # --bee=$(if use fullbee; then echo full; else echo partial; fi) \
-        }
+  src_configure() {
+  # Bigloo doesn't use autoconf and consequently a lot of options used by econf give errors
+  # Manuel Serrano says: "Please, dont talk to me about autoconf. I simply dont want to hear about it..."
+  ./configure \
+          $(use java && echo "--jvm=yes --java=$(java-config --java) --javac=$(java-config --javac)") \
+          --prefix=/usr \
+          --mandir=/usr/share/man \
+          --infodir=/usr/share/info \
+          --libdir=/usr/$(get_libdir) \
+          --docdir=/usr/share/doc/${PF} \
+          --benchmark=yes \
+          --sharedbde=no \
+          --sharedcompiler=no \
+          --coflags="" || die "configure failed"
+          # --bee=$(if use fullbee; then echo full; else echo partial; fi) \
+  }
 
-        src_compile() {
-                if use emacs; then
-                        elisp-compile etc/*.el || die "elisp-compile failed"
-                fi
+  src_compile() {
+          if use emacs; then
+                  elisp-compile etc/*.el || die "elisp-compile failed"
+          fi
 
-                # parallel build is broken
-                emake -j1 || die "emake failed"
-        }
+          # parallel build is broken
+          emake -j1 || die "emake failed"
+  }
 
-        src_install () {
-                # dodir /etc/env.d
-                # echo "LDPATH=/usr/$(get_libdir)/bigloo/${PV}/" > ${D}/etc/env.d/25bigloo
+  src_install () {
+          # dodir /etc/env.d
+          # echo "LDPATH=/usr/$(get_libdir)/bigloo/${PV}/" > ${D}/etc/env.d/25bigloo
 
-                # make the links created not point to DESTDIR, since that is only a temporary home
-                sed 's/ln -s $(DESTDIR)/ln -s /' -i Makefile.misc
-                emake -j1 DESTDIR="${D}" install || die "install failed"
+          # make the links created not point to DESTDIR, since that is only a temporary home
+          sed 's/ln -s $(DESTDIR)/ln -s /' -i Makefile.misc
+          emake -j1 DESTDIR="${D}" install || die "install failed"
 
-                if use emacs; then
-                        elisp-install ${PN} etc/*.{el,elc} || die "elisp-install failed"
-                        elisp-site-file-install "${FILESDIR}/${SITEFILE}"
-                fi
+          if use emacs; then
+                  elisp-install ${PN} etc/*.{el,elc} || die "elisp-install failed"
+                  elisp-site-file-install "${FILESDIR}/${SITEFILE}"
+          fi
 
-                # einfo "Compiling bee..."
-                # emake compile-bee || die "compiling bee failed"
-        }
+          # einfo "Compiling bee..."
+          # emake compile-bee || die "compiling bee failed"
+  }
 
-        pkg_postinst() {
-                use emacs && elisp-site-regen
-        }
+  pkg_postinst() {
+          use emacs && elisp-site-regen
+  }
 
-        pkg_postrm() {
-                use emacs && elisp-site-regen
-        }
+  pkg_postrm() {
+          use emacs && elisp-site-regen
+  }
 symbols:
-        "DESTDIR": "${D}"
+  DESTDIR: ${D}
